SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Table_1](
	[col1] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[col2] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[col3] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)

GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [index1] ON [dbo].[Table_1]
(
	[col1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
GO
